### ISSUE TITLE
Redundant `<C-i>` mapping breaks jump list movement

### ISSUE THREAD

**Issue by ondras12345** [dracula/zathura#1]
Hi, thanks for the great color scheme.
`<C-r>` seems to be the default mapping for recolor, and `<C-i>` is really useful in combination with `<C-o>` to move through the jump list.
Would you please consider commenting this line out, so that the redundant mapping does not replace the default one if the user does not specifically want to do so?
https://github.com/dracula/zathura/blob/f74476393105b7c45d2496385a3f5994d312ae1e/zathurarc#L4

**Comment by ethancedwards8** [comment]
Thanks for the issue and using my theme! I didn't realize this was a problem, I'll be sure to fix it :)
